INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Cesar Blandon Gordon", "0", 50098016, "Pescaderia 2 Mares"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Sohamy Diana Gonzales", "1-1039-0281", 57015729, "Cafe House"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Patzy Allegro", "0", 57040596, "Allegro"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Enano Brayan ", "0", 60081809, "Millar"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Wilson Soto Sancho", "0", 60922788, "Vibes"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Pedro Gomez Rodriguez", "0", 60970902, "Nachoz  Cocinero"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Mama Nubia", "0", 61027129, "Carniceria Chacon"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Maria Jose Tijerino ", "0", 61823990, "Subway"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Anfernne Gerardo Ocampo Miranda", "4-236-941", 61909120, "Rodolfo leiton"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Josselinne Mayela Mena Badilla", "4-232-227", 61976128, "Fusion Desing"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Faicely Acevedo ", "0", 62125407, "Don Hermes"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Melvin Hilberth Barrios ", "1-1504-0473", 63281873, "Veterinaria Mall"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Alvaro Giacomo rec Alejandra", "0", 63519970, "Cafe House"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Kimberly Daniela Gutierres Rodriguez", "7-229-969", 70207804, "Fusion Desing"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Michael Antonio Marin Espinoza", "1-1339-812", 70478284, "Seguridad Vibes"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Dave Angel España Rodriguez ", "C-01479289", 70672374, "Barberia "  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Ronald Francisco Campos Barquero", "4-156-511", 70881264, "Aseo Paseo"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Vanessa Bonilla Garro", "1-156-549", 71084860, "Eurocronos"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Jefry Berrocal Aguero", "1-990-247", 71621639, "Transoto Abogado "  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Cristian Fernando Hermano de Navarro", "1-1379-2925", 71702925, ""  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Chichi Mauricio Garita", "0", 71780519, "DJ Ottos"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Pamela Alejandra Suñiga Bolaños", "0", 71989043, "Quiqsilver"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Vera Viquez", "0", 72033990, "Ferreteria San Marcos"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Rony Benavidez mama Nubia", "0", 72982684, "Carniceria Chacon"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Flori Maria Rodriguez Gomez", "5-156-657", 83170999, "Ventium Medica"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Shirley Guevara Ramirez", "4-0171-0018", 83240979, "Piratas"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Randall Campos Zamora", "4-162-262", 83250193, "La Fama"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Evelinda ", "0", 83380983, "Orange "  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Andrea de los Angeles ", "4-231-781", 83445812, "Fusion"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Alvaro Viquez Segura", "1-863-395", 84240908, "Ferreteria Navarro"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Jose Angel Navarro Rodriguez", "1-1708-0386", 84249022, "Zapateria Eurocronos"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Xiomara Piratas", "0", 84285115, "Piratas"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Juan Augusto Rodriguez Reyes ", "RP-155810776726", 84379796, "Carniceria La Fama"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Marggi Sancho Diaz// Margareth", "1-0939-0514", 85307031, "Serpentinas"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Cristofer Leiton Montenegro", "0", 85372151, "Carniceria Castillo"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Yajaira Barrantes Chacon", "1-1683-0111", 85489102, "Fusion Desing"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Josue Ovando Cerrano", "0", 85742527, "Amnesia"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Laaura Vanesa Camacho Villalobos", "4-0170-0210", 85878485, "Piratas"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Fabiola Nelson", "0", 85901667, "Fusion"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Marlon ", "0", 86258670, "Garper"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Jaime Jose Barboza Hernandez", "1-1135-0742", 87044625, "Rosabal"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Mileska de los Angeles Brenes Montenegro", "1-1582-0904", 87203677, "Eurocronos"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Ana Cristina Rios Mena", "2-378-406", 87633614, "Leandro"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Norma Bonilla Hernandez", "0", 87802992, "Torres del lago"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Andrea Quezada Aguilar", "0", 88553444, "OPS"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Claudia Patricia Blanco", "0", 88649119, "OPS"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Jeimy Cuba", "0", 88787180, "Eurocronos"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Ana Catalina Gomez Mama", "1-1498-0141", 89030209, ""  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Krishel Lissette Venegas Vargas", "7-234-467", 01, "Quiqsilver"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Mariani Serpentinas", "0", NULL, "Serpentinas"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Yendry hermana Samy Marco Paniagua", "0", NULL, "Garper"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Dany lavacar Natalia", "0", NULL, "lavacar Natalia"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Natanael", "0", NULL, "PLS"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Cristian Damond Quiel", "0", NULL, "PLS alejo"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Georgina Mama", "0", NULL, ""  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Georgina Mama", "0", NULL, ""  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Magaly Prima Marielos Pablo", "0", NULL, "Gente Natalia"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Jesica Mani Familia Natalia ", "0", NULL, "Familia Natalia"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Teresita", "0", NULL, "Bijoux"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Adriana Titi", "0", NULL, "Familia Natalia"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Papa de Estivalis ", "0", NULL, "Gente Natalia"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Carmen Masis ", "0", NULL, "Gente Natalia"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Doña.Deicy", "0", NULL, "Azafran"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Alejandra Cafe House", "0", NULL, "Cafe House"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Andrea Calderon Cordero", "0", NULL, "Gente Natalia"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Edwin Alberto Cruz Cruz", "0", NULL, "Fusion Desing"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Niko Oclock", "0", NULL, "Oclock"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Mauricio Daniel", "0", NULL, "Pizzeria San Rafael"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Jorge Garita ", "0", NULL, ""  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Jose Antonio Gomez Paniagua", "0", NULL, "Busetas Tibas"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Orlando Peluqueria", "0", NULL, "Peluqueria D Maira"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Acevedo La 400", "0", NULL, "La 400"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Libardo", "0", NULL, "Panaderia Libardo"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Alonso La 400", "0", NULL, "La 400"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Karla", "0", NULL, "Ro-Hermana"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Xiaupeng Lai Pan", "0", NULL, "Chino Aurora"  );
INSERT INTO `clients` (`first_name`, `ssn`, `phone`, `address_work`) VALUES ( "Vivian ", "0", NULL, "Ferreteria  "  );